
language: minimal
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: ['gfortran-6','liblapack-dev','libmumps-dev','libopenmpi-dev','octave']

matrix:
  include:
  - os: linux
# works on osx, but takes 10 minutes to build on Travis-CI
#  - os: osx
#    - brew install gcc
#    - brew install lapack openblas open-mpi scalapack
#    - brew tap dpo/openblas
#    - brew install mumps


install:
- cd $TRAVIS_BUILD_DIR/build
- cmake -DNP=2 ..
- cmake --build . --parallel

script: ctest -R 2D --parallel --output-on-failure
