runs:

  using: "composite"

  steps:

  - name: Install packages (Linux)
    shell: bash
    if: runner.os == 'Linux'
    run: |
      sudo apt update
      sudo apt install --no-install-recommends libopenmpi-dev openmpi-bin libhdf5-dev ninja-build

  - name: Install packages (MacOS)
    shell: bash
    if: runner.os == 'macOS'
    run: brew install ninja open-mpi hdf5 scalapack

  - name: Configure multi
    shell: bash
    run: $CMAKE --preset multi -Dhwm14:BOOL=${{ matrix.hwm14 }}

  - name: print config log
    shell: bash
    if: ${{ failure() }}
    run: cat build/CMakeFiles/CMakeConfigureLog.yaml


  - name: Debug build
    shell: bash
    run: $CMAKE --build --preset debug

  - name: Debug unit test
    shell: bash
    run: $CTEST --preset debug -L unit

  # - name: Debug core test
  #   shell: bash
  #   run: $CTEST --preset debug -LE unit -R "(2dew_.*fang|2dns_.*fang)"


  - name: Release build
    shell: bash
    run: $CMAKE --build --preset release

  - name: Release unit test
    shell: bash
    run: $CTEST --preset release -L unit

  # - name: Release core test
  #   shell: bash
  #   run: $CTEST --preset release -LE unit -E 3d
