name: ci

env:
  CTEST_PARALLEL_LEVEL: 0
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CMAKE_INSTALL_PREFIX: ~/libs
  CMAKE_PREFIX_PATH: ~/libs

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - "CMakePresets.json"
      - "cmake/libraries.json"
      - "!cmake/intel.cmake"
      - ".github/workflows/ci.yml"
# paths ignore starting with "!"
      - "!docs/**"
      - "!**/cray.cmake"


jobs:

  cmake-320:
    timeout-minutes: 30

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Install CMake 3.20
      run: |
        curl -LO "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-linux-x86_64.tar.gz"
        tar -xf cmake-3.20.6-linux-x86_64.tar.gz

    - name: CMake path
      run: |
        echo "CMAKE=$GITHUB_WORKSPACE/cmake-3.20.6-linux-x86_64/bin/cmake" >> $GITHUB_ENV
        echo "CTEST=$GITHUB_WORKSPACE/cmake-3.20.6-linux-x86_64/bin/ctest" >> $GITHUB_ENV

    - name: echo CMake version
      run: $CMAKE --version

    - uses: ./.github/workflows/composite-linux


  core:
    timeout-minutes: 30

    strategy:
      matrix:
        hwm14: [false]
        os: [ubuntu-latest]
        gcc: [9,10,11,12,13]
# glitch with ffilesystem GA macOS not detecting HAVE_CXX_FILESYSTEM never seen on real computers
        # include:
        # - os: macos-latest
        #   gcc: 13
        include:
        - os: ubuntu-20.04
          gcc: 8

    env:
      CC: gcc-${{ matrix.gcc }}
      CXX: g++-${{ matrix.gcc }}
      FC: gfortran-${{ matrix.gcc }}
      CMAKE: cmake
      CTEST: ctest

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v4

    - name: Install GCC-8 (Ubuntu 20.04)
      if: matrix.os == 'ubuntu-20.04'
      timeout-minutes: 15
      run: sudo apt install gcc-8 g++-8 gfortran-8
# don't install libscalapack-openmpi-dev, it is broken CMake package
# don't remove sudo apt update or every once in a while all the jobs will fail when the GA runner
# is out of sync with the upstream Ubuntu package repos

    - uses: ./.github/workflows/composite-linux
