name: ci

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 2

on:
  push:
    paths:
      - "**.c"
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - "!cmake/compilers/intel.cmake"
      - ".github/workflows/ci.yml"
# paths ignore starting with "!"
      - "!docs/**"


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo $(cmake -P scripts/requirements.cmake)

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install numeric libraries
      timeout-minutes: 8
      run: |
        cmake -S $GITHUB_WORKSPACE/gemext -B $GITHUB_WORKSPACE/gemext/build --install-prefix=${HOME}/gemlibs
        cmake --build $GITHUB_WORKSPACE/gemext/build --target msis
        cmake --install $GITHUB_WORKSPACE/gemext/build

    - name: Configure multi
      run: cmake --preset multi -DCMAKE_PREFIX_PATH:PATH=${HOME}/gemlibs

    - name: Debug build
      run: cmake --build --preset debug

    - name: Debug unit test
      run: ctest --preset debug -L unit --output-junit test-debug-unit.xml

    - name: Debug core test
      run: ctest --preset debug -LE unit -R "(2dew_fang|2dns_fang)" --output-junit test-debug-core.xml


    - name: Release build
      run: cmake --build --preset release

    - name: Release unit test
      run: ctest --preset release -L unit --output-junit test-release-unit.xml

    - name: Release core test
      run: ctest --preset release -LE unit -E 3d --output-junit test-release-core.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: build/test-*.xml

  linux-build-most:
    # build critical libraries like scalapack and mumps, skipping others for time
    needs: linux
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install libhwloc-dev libhdf5-dev liblapack-dev libopenmpi-dev openmpi-bin

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install numeric libraries
      timeout-minutes: 8
      run: |
        cmake -S $GITHUB_WORKSPACE/gemext -B $GITHUB_WORKSPACE/gemext/build --install-prefix=${HOME}/gemlibs
        cmake --build $GITHUB_WORKSPACE/gemext/build --target mumps h5fortran msis
        cmake --install $GITHUB_WORKSPACE/gemext/build

    - name: Configure build
      run: cmake -B build -DCMAKE_PREFIX_PATH:PATH=${HOME}/gemlibs

    - name: Build
      run: cmake --build build

    - name: Unit tests
      run: ctest --test-dir build -L unit

    - name: core tests
      run: ctest --test-dir build -LE unit -E 3d


  MSIS-20:
    needs: linux
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo $(cmake -P scripts/requirements.cmake)

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install numeric libraries
      timeout-minutes: 8
      run: |
        cmake -S $GITHUB_WORKSPACE/gemext -B $GITHUB_WORKSPACE/gemext/build --install-prefix=${HOME}/gemlibs
        cmake --build $GITHUB_WORKSPACE/gemext/build --target msis
        cmake --install $GITHUB_WORKSPACE/gemext/build

    - name: Configure release
      run: cmake -B build --preset release -DCMAKE_PREFIX_PATH:PATH=${HOME}/gemlibs -Dmsis2:BOOL=true

    - name: Build release
      run: cmake --build build

    - name: Release unit test
      run: ctest --test-dir build --preset default -L unit

    - name: Release core test
      run: ctest --test-dir build --preset default -LE unit -E 3d


  HWM14:
    needs: linux
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo $(cmake -P scripts/requirements.cmake)

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install numeric libraries
      timeout-minutes: 8
      run: |
        cmake -S $GITHUB_WORKSPACE/gemext -B $GITHUB_WORKSPACE/gemext/build --install-prefix=${HOME}/gemlibs
        cmake --build $GITHUB_WORKSPACE/gemext/build --target msis hwm14
        cmake --install $GITHUB_WORKSPACE/gemext/build

    - name: Configure release
      run: cmake -B build --preset release -DCMAKE_PREFIX_PATH:PATH=${HOME}/gemlibs -Dhwm14:BOOL=true

    - name: Build release
      run: cmake --build build

    - name: Release unit test
      run: ctest --test-dir build --preset default -L unit

    - name: Release core test
      run: ctest --test-dir build --preset default -LE unit -E 3d


  macos:
    runs-on: macos-latest
    needs: linux

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: $(cmake -P scripts/requirements.cmake)
      timeout-minutes: 15

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install numeric libraries
      timeout-minutes: 8
      run: |
        cmake -S $GITHUB_WORKSPACE/gemext -B $GITHUB_WORKSPACE/gemext/build --install-prefix=${HOME}/gemlibs
        cmake --build $GITHUB_WORKSPACE/gemext/build --target msis
        cmake --install $GITHUB_WORKSPACE/gemext/build

    - name: Configure multi
      run: cmake --preset multi -DCMAKE_PREFIX_PATH:PATH=${HOME}/gemlibs

    - name: Debug build
      run: cmake --build --preset debug

    - name: Debug unit test
      run: ctest --preset debug -L unit

    - name: Debug core test
      run: ctest --preset debug -LE unit -R "(2dew_fang|2dns_fang)"


    - name: Release build
      run: cmake --build --preset release

    - name: Release unit test
      run: ctest --preset release -L unit

    - name: Release core test
      run: ctest --preset release -LE unit -E 3d
