name: ci_debug_build

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - ".github/workflows/ci_debug_build.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran liblapack-dev libscalapack-openmpi-dev libmumps-dev libopenmpi-dev openmpi-bin libhdf5-dev

    - run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - run: ctest -S setup.cmake -R unit -V
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_DebugBuildlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest -S setup.cmake -R 2d_fang -V
