name: ci_linux

env:
  DEBIAN_FRONTEND: noninteractive

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"

jobs:

  cmake313-hdf5:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Get CMake 3.13
      run: |
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.tar.gz
        tar -xf cmake-3.13.4-Linux-x86_64.tar.gz
        echo "${GITHUB_WORKSPACE}/cmake-3.13.4-Linux-x86_64/bin" >> $GITHUB_PATH

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo cmake -P scripts/gemini_prereq.cmake

# CI is too slow for 3d_glow
    - run: cmake -B build
    - run: cmake --build build --parallel

    - run: ctest -E 3d --parallel 4 --output-on-failure
      working-directory: build


  debug:
    needs: cmake313-hdf5
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo cmake -P scripts/gemini_prereq.cmake

    - run: cmake -B build -DCMAKE_BUILD_TYPE=Debug
    - run: cmake --build build --parallel

    - run: ctest -R unit --parallel 4 --output-on-failure
      working-directory: build

    - run: ctest -R 2dew_fang --parallel 4 --output-on-failure
      working-directory: build
