name: ci_linux
env:
  FC: gfortran
  CC: gcc
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"


jobs:

  hdf5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends pkg-config gfortran libopenmpi-dev liblapack-dev libscalapack-openmpi-dev libmumps-dev libhdf5-dev
        python -m pip install ninja

# CI is too slow for 3d_glow
    - run: ctest -S setup.cmake -E 3d -VV
