name: ci_linux
env:
  FC: gfortran
  CC: gcc

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"


jobs:

  hdf5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends pkg-config gfortran libopenmpi-dev liblapack-dev libscalapack-openmpi-dev libmumps-dev libhdf5-dev

# CI is too slow for 3d_glow
    - run: ctest -S setup.cmake -E 3d -VV


  autobuild_no_mpi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: build and test without MPI
      run: ctest -S setup.cmake -R unit -VV

    - name: 2D test without MPI
      run: ctest -R 2dew_fang -V
      working-directory: build


  autobuild_mpi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev

    - run: ctest -S setup.cmake -R unit -V

    - run: ctest -S setup.cmake -E 3d -V
