name: ci_linux

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"


jobs:

  hdf5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends pkg-config gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-openmpi-dev libmumps-dev libhdf5-dev

# CI is too slow for 3d_glow
    - run: ctest -S setup.cmake -E 3d -VV
      env:
        FC: gfortran

  no_mpi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libhdf5-dev

    - name: build without MPI
      run: |
        cmake -B build -Dno_mpi:BOOL=true
        cmake --build build

    - name: test without MPI
      run: ctest -V
      working-directory: build

  cmakeBuildAllLibs:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends pkg-config gfortran libopenmpi-dev openmpi-bin

    - run: ctest -S setup.cmake -E 3d_glow -V
      env:
        FC: gfortran
