name: ci_linux
env:
  cmake_version: '3.15.4'
  CI: true

on:
  push:
    paths-ignore:
      - "**/*.py"
      - "**/*.md"
      - "**/*.m"
  pull_request:
    paths-ignore:
      - "**/*.py"
      - "**/*.md"
      - "**/*.m"

jobs:

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install -e .[tests]
    - run: sudo apt install -yq --no-install-recommends ninja-build gfortran liblapack-dev libscalapack-mpi-dev libmumps-dev libopenmpi-dev openmpi-bin
    - name: Setup CMake
      run: |
        pip install cmakeutils
        cmake_setup ${cmake_version} --prefix ${HOME}/.local
        ${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin/cmake -B build
      env:
        FC: gfortran
    - run: ${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin/cmake --build build --parallel
# CI is too slow for 3d_glow
# -V output truncated on CI?
    - run: ${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin/ctest --parallel --output-on-failure -E 3d_glow
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Cmake_log
        path: build/CMakeFiles/CMakeError.log

  meson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson
    - run: pip install -e .[tests]
    - run: sudo apt install -yq --no-install-recommends ninja-build gfortran libopenmpi-dev openmpi-bin
    - run: meson setup build
      env:
        FC: gfortran
    - run: ninja -C build
    - run: meson test -C build --suite unit -v
    - run: meson test -C build --suite 2d_fang -v
    - run: meson test -C build --suite 2d_glow -v
# CI is too slow for 3d_glow
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
