name: ci_linux

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"
  pull_request:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"

jobs:

  hdf5:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-openmpi-dev libmumps-dev libhdf5-dev

# CI is too slow for 3d_glow
    - run: cmake -B build
    - run: cmake --build build
    - run: ctest -E 3d --output-on-failure
      working-directory: build


  debug:
    needs: hdf5
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-openmpi-dev libmumps-dev libhdf5-dev

    - run: cmake -B build -DCMAKE_BUILD_TYPE=Debug
    - run: cmake --build build

    - run: ctest -R unit --output-on-failure
      working-directory: build

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_DebugBuildlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest -R 2dew_fang --output-on-failure
      working-directory: build


  autobuild_no_mpi:
    needs: debug
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - run: cmake -B build

    - run: cmake --build build

    - name: unit tests
      run: ctest -R unit --output-on-failure
      working-directory: build

    - name: 2D test without MPI
      run: ctest -R 2dew_fang --output-on-failure
      working-directory: build


  autobuild_mpi:
    needs: debug
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # have to have openmpi-bin as unlike full install it's not auto-installed here
    # libhdf5-dev just to speed up CI
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin libhdf5-dev

    - run: ctest -S setup.cmake -R unit -VV

    - run: ctest -E 3d -V
      working-directory: build
