name: ci_macos
env:
  CI: true

on:
  push:
    paths-ignore:
      - "**/*.py"
      - "**/*.md"
      - "**/*.m"
  pull_request:
    paths-ignore:
      - "**/*.py"
      - "**/*.md"
      - "**/*.m"

jobs:

  macosMeson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: pip install -e .[tests]
    - run: brew install gcc ninja open-mpi lapack
    - run: meson setup build
      env:
        FC: gfortran-9
        CC: gcc-9
    - run: ninja -C build
    - run: meson test -C build --suite unit -v
    - run: meson test -C build --suite 2d_fang -v
    - run: meson test -C build --suite 2d_glow -v
# CI is too slow for 3d_glow
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt

  macosCmake:
    # works but takes 3-4 times as long as Meson--conserving CI resources
    if: false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: pip install -e .[tests]
    - name: Install dependencies
      run: |
        brew install gcc lapack open-mpi
        brew tap dpo/openblas
        brew install mumps
    - run: cmake -B build
      env:
        FC: gfortran-9
        CC: gcc-9
    - run: cmake --build build --parallel
# CI is too slow for 3d_glow
    - run: ctest --parallel -E 3d_glow --output-on-failure
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Cmake_Testlog
        path: build/CMakeFiles/CMakeError.log
