name: ci_macos
env:
  CMAKE_GENERATOR: Ninja
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"
  pull_request:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"

jobs:

  hdf5:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - run: brew install gcc ninja lapack open-mpi hdf5 scalapack
      timeout-minutes: 5
      # transient CI download speed

# CI is too slow for 3d_glow

    - run: cmake -B build
      timeout-minutes: 2

    - run: cmake --build build
      timeout-minutes: 5

    - run: ctest -E 3d --parallel 4 --output-on-failure
      working-directory: build
      timeout-minutes: 5

  no_mpi:
    needs: hdf5
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    # leave as 3.7 to avoid pip install in 3.8 but run in 3.7

    - run: brew install gcc ninja lapack hdf5
      timeout-minutes: 5
      # transient CI download speed

    - run: cmake -B build
      timeout-minutes: 2

    - run: cmake --build build
      timeout-minutes: 5

    - name: Unit tests
      run: ctest -R unit --parallel 4 --output-on-failure
      working-directory: build
      timeout-minutes: 2

    - name: 2D test without MPI
      run: ctest -R 2dew_fang --parallel 4 --output-on-failure
      working-directory: build
      timeout-minutes: 5
