name: ci_macos
env:
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"
  pull_request:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"

jobs:

  hdf5:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - run: brew install gcc ninja lapack open-mpi hdf5 scalapack

# CI is too slow for 3d_glow

    - run: ctest -S setup.cmake -R unit -VV

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_CMake_Unit_log
        path: build/CMakeFiles/CMakeError.log

    - run: ctest -E 3d --parallel 2 -V
      working-directory: build

  no_mpi:
    needs: hdf5
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    # leave as 3.7 to avoid pip install in 3.8 but run in 3.7

    - run: brew install gcc ninja lapack hdf5

    - name: build and test without MPI
      run: ctest -S setup.cmake -R unit -VV

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_noMPI_Unit_log
        path: build/CMakeFiles/CMakeError.log

    - name: 2D test without MPI
      run: ctest -R 2dew_fang --parallel 2 -V
      working-directory: build
