name: ci_macos
env:
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"

jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    # leave as 3.7 to avoid pip install in 3.8 but run in 3.7
    - run: python -m pip install -e .
    - run: brew install pkg-config ninja lapack open-mpi hdf5 scalapack

# CI is too slow for 3d_glow
    - run: ctest -S setup.cmake -E 3d -VV
      env:
        FC: gfortran-9
        CC: gcc-9
