name: ci_windows
env:
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"


jobs:

  no_mpi:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-hdf5
          mingw-w64-x86_64-lapack
          mingw-w64-x86_64-python-h5py
          mingw-w64-x86_64-python-scipy

    - uses: actions/checkout@v2

    - run: ctest -S setup.cmake -E 3d -VV
