name: intel-oneapi

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 2
  CC: icx
  FC: ifort

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - "!cmake/compilers/gnu.cmake"
      - ".github/workflows/intel-oneapi.yml"
# paths ignore starting with "!"
      - "!docs/**"
      - "!scripts/**"

jobs:

  linux-intel-oneapi:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Intel Apt repository
      timeout-minutes: 1
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update

    - name: Install Intel oneAPI
      timeout-minutes: 10
      run: sudo apt-get install intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-mpi intel-oneapi-mpi-devel intel-oneapi-mkl intel-oneapi-mkl-devel ninja-build

    - name: Setup Intel oneAPI environment
      run: |
        source /opt/intel/oneapi/setvars.sh
        printenv >> $GITHUB_ENV

# HDF5 library doesn't install correctly with Ninja Multi-config
# CMake Error at fortran/src/cmake_install.cmake:61 (file):
#  file INSTALL cannot find
#  "build/HDF5-prefix/src/HDF5-build/bin/static/Debug/h5fortran_types.mod":

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install numeric libraries
      timeout-minutes: 8
      run: |
        cmake -S $GITHUB_WORKSPACE/gemext -B $GITHUB_WORKSPACE/gemext/build --install-prefix=${HOME}/gemlibs
        cmake --build $GITHUB_WORKSPACE/gemext/build --target glow msis mumps
        cmake --install $GITHUB_WORKSPACE/gemext/build

    - name: CMake Configure Ninja Multi-config
      run: cmake --preset multi -DCMAKE_PREFIX_PATH:PATH=${HOME}/gemlibs || cmake --preset multi -DCMAKE_PREFIX_PATH:PATH=${HOME}/gemlibs --debug-find

    - name: DEBUG build
      run: cmake --build --preset debug
    - name: DEBUG unit test
      run: ctest --preset debug -L unit
    - name: DEBUG test core
      run: ctest --preset debug -LE unit -E 3d

    - name: RELEASE build
      run: cmake --build --preset release
    - name: RELEASE unit test
      run: ctest --preset release -L unit
    - name: RELEASE test core
      run: ctest --preset release -LE unit -E 3d
